baseurl = "/"
title = "Test site"
copyright = "Copyright В© 2018, Copyright Owner Name"
languageCode = "en-US"
theme = "indigo"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
  Author = "Site Author Name"
  Description = "Description of website for head meta tag"
  Subtitle = "A subtitle for your site"
  Avatar = "images/site-logo.svg"
  Biography = "A short description, a few sentences describing the author. Set the 'ShowBio' parameter to false to hide this."
  ShowBio = true
  PermalinkText = "рџ”—"

  # Contact/social-network identifiers for social icons
  EmailAddress = "email.address@example.com"
  FacebookUser = "FacebookUserName"
  FlickrUser = "FlickrUserName"
  GitHubUser = "GitHubUserName"
  GitLabUser = "GitLabUserName"
  GlitchUser = "GlitchUserName"
  KeybaseUser = "KeybaseUserName"
  MicroBlogUser = "MicroBlogUserName"
  StackOverflowUser = "StackOverflowUserName"
  TumblrUser = "TumblrUserName"
  TwitterUser = "TwitterUserName"

  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]  
    EmailAddress = "email.address@example.com"
    FlickrUser = "FlickrUserName"
    GitHubUser = "GitHubUserName"
    TwitterUser = "TwitterUserName"
    MicroBlogUser = "MicroBlogUserName"
    Country = "CountryName"
    City = "CityName"